# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
 - script: |
              ls $(System.DefaultWorkingDirectory)
              echo "terraform build started.."
              cd $(System.DefaultWorkingDirectory)/src
              echo "list all the files"
              ls -la 
   displayName: 'Setup Enviroment'

 - task: CopyFiles@2
   inputs:
      SourceFolder: 'src'
      Contents: |
                 **/*
                      !dev/.terraform/**/*
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
   displayName: 'Copy Artifacts'

 - publish: '$(Build.ArtifactStagingDirectory)'
   artifact: artifacts