version: 0.2

# run-as: Linux-user-name

env:
  shell: bash
  # variables:
  #   key: "value"
  # parameter-store:
  #   key: "value"
  # exported-variables:
  #   - variable
   
  # secrets-manager:
  #   key: aws-fargate
    
  # git-credential-helper: no | yes

# proxy:
#   upload-artifacts: no | yes
#   logs: no | yes


        
phases:
  install:
    # run-as: Linux-user-name
    on-failure:  CONTINUE
    # runtime-versions:
    #   terraform: 1.3.4
    commands:
    - wget https://releases.hashicorp.com/terraform/1.3.4/terraform_1.3.4_linux_amd64.  
    - unzip terraform_1.3.4_linux_amd64.zip
    - sudo mv terraform /usr/local/bin/
    - terraform version
      
    finally:
    - terraform init
      
    # steps:
  pre_build:
    # run-as: Linux-user-name
    on-failure: CONTINUE
    commands:
    - cd $CODEBUILD_SRC_DIR/src
  
    # finally:
    #   - command
    #   - command
    # steps:
  build:
    # run-as: Linux-user-name
    on-failure: CONTINUE
    commands:
    - terraform validate
     
    finally:
    - terraform plan
    # steps:
#   post_build:
#     run-as: Linux-user-name
#     on-failure: ABORT | CONTINUE
#     commands:
#       - command
#       - command
#     finally:
#       - command
#       - command
#     # steps:
# reports:
#   report-group-name-or-arn:
#     files:
#       - location
#       - location
#     base-directory: location
#     discard-paths: no | yes
#     file-format: report-format
artifacts:
  files:
    - '**/*'
 
  name: fargate
#   discard-paths: no | yes
#   base-directory: location
#   exclude-paths: excluded paths
#   enable-symlinks: no | yes
#   s3-prefix: prefix
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       name: secondary-artifact-name
#       discard-paths: no | yes
#       base-directory: location

# cache:
#   paths:
#     - path
#     - path
